apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jcloudcodes/jcloud_argocd.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
        - environments/qa/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: django-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
