apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
  DJANGO_DEBUG: {{ .Values.env.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  {{- if .Values.postgres.enabled }}
  DB_HOST: {{ printf "%s-postgres" (include "django-app.fullname" .) | quote }}
  DB_PORT: {{ .Values.postgres.service.port | quote }}
  DB_NAME: {{ .Values.postgres.auth.database | quote }}
  DB_USER: {{ .Values.postgres.auth.username | quote }}
  {{- end }}
