{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}-postgres
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        {{- include "django-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}

            # Use Secret for password (do NOT store plain text in values for GitOps)
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-app.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: {{ .Values.postgres.persistence.pgdata | default "/var/lib/postgresql/data/pgdata" | quote }}

          readinessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 15
            periodSeconds: 10

          volumeMounts:
            {{- if .Values.postgres.persistence.enabled }}
            - name: data
              mountPath: /var/lib/postgresql/data
            {{- end }}

      volumes:
        {{- if .Values.postgres.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "django-app.fullname" . }}-postgres
        {{- end }}
{{- end }}