apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8000 }}
      targetPort: http
  selector:
    {{- include "django-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web